### ISSUE TITLE
[Bug] Copiing a rail will mess up its render/LOD

### ISSUE THREAD

**Issue by TuTAH1** [Epp-s-Satisfactory-Mods/UseSampledOrientation#1]
If you copy the rail and build it with mod installed, the orange building hologram will look like 90 degree rotated, but when it disappears, rail builded as it should be. Except the parts of rails disappear in front of my eyes. If you build it by just choosing an item in the build menu, not copying it (or copy it without the mod installed), the orange hologram will be fine and the rail rendering/LOD will be fine, without disappearing parts.

https://github.com/user-attachments/assets/086bd59d-4f05-4e29-8b0c-9526012cd73e
(compressed it to fit 10 MB)

**Comment by Epp-code** [comment]
I've noticed the same thing.  There really aren't many dials to tweak in the code and the hologram orientation system is pretty wonky, IMO.  Since it's just a visual artifact and I don't know where/how to investigate, I don't plan on trying to fix it.  Thanks for the report, though.
