### ISSUE TITLE
Game crash on sampling a belt

### ISSUE THREAD

**Issue by leatherneck6017** [Epp-s-Satisfactory-Mods/UseSampledOrientation#2]
Pretty reproduceable. SMM debug file attached.
[SMMDebug-2024-11-07-04-30-44.zip](https://github.com/user-attachments/files/17656072/SMMDebug-2024-11-07-04-30-44.zip)

**Comment by Epp-code** [comment]
This is probably because of the patch yesterday.  Looking into it!

**Comment by Epp-code** [comment]
Yeah, that seems to be the issue.  I rebuilt against the current version of the game and it seemed to fix things for me.  Building for release now and will have it uploaded on the mod manager as soon as I can.

**Comment by Epp-code** [comment]
Ok, v0.2.1 is uploaded and should work with the latest version of the game.

**Comment by leatherneck6017** [comment]
Thanks for the quick fix.
